apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  ports:
  - name: tcp-client
    port: 9090
    protocol: TCP
    targetPort: 9090
    nodePort: 31001
  type: NodePort
  selector:
    app: prometheus
